apiVersion: v1
kind: Secret
metadata:
  name: mock-apps-secrets
data:
  {{ .Values.backend.secrets.version_key }}: {{ .Values.backend.secrets.version_value | b64enc }}
  {{ .Values.backend.secrets.postgres_db_key }}: {{ .Values.backend.secrets.postgres_db_value | b64enc }}
  {{ .Values.backend.secrets.postgres_user_key }}: {{ .Values.backend.secrets.postgres_user_value | b64enc }}
  {{ .Values.backend.secrets.postgres_password_key }}: {{ randAlphaNum 16 | b64enc }}
  {{ .Values.backend.secrets.postgres_host_key }}: {{ .Values.backend.secrets.postgres_host_value | b64enc }}
  {{ .Values.backend.secrets.postgres_port_key }}: {{ .Values.backend.secrets.postgres_port_value | b64enc }}
  {{ .Values.backend.secrets.redis_host_key }}: {{ .Values.backend.secrets.redis_host_value | b64enc }}
  {{ .Values.backend.secrets.redis_port_key }}: {{ .Values.backend.secrets.redis_port_value | b64enc }}
