name: Build on Push

on:
  push:
    branches: [ '**' ]

env:
  DOCKER_REGISTRY: ghcr.io/vlarkin

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short $GITHUB_REF_NAME)" >> $GITHUB_ENV
      -
        name: Build and push Docker image - frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/frontend:${{ env.IMAGE_TAG }}
      -
        name: Build and push Docker image - backend
        uses: docker/build-push-action@v3
        with:
          context: backend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/backend:${{ env.IMAGE_TAG }}
      -
        name: Update helm/values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i ".frontend.image_tag=strenv(IMAGE_TAG) | .backend.image_tag=strenv(IMAGE_TAG) | .backend.secrets.version_value(IMAGE_TAG)" helm/values.yaml
      -
        name: Push updates to the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "[skip actions] Update helm/values.yaml"
          git push

