name: Build on Push

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract short commit SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short $GITHUB_REF_NAME)" >> $GITHUB_ENV
      -
        name: Build and push Docker image frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          push: true
          tags: $DOCKER_REGISTRY/frontend:$IMAGE_TAG
      -
        name: Build and push Docker image backend
        uses: docker/build-push-action@v3
        with:
          context: backend/
          push: true
          tags: $DOCKER_REGISTRY/backend:$IMAGE_TAG


